'use strict';

exports.GetLeaguel = () => {
    return [
            {
                "leagueId": 1,
                "color": "#9933FF",
                "nameEn": "Ireland Premier Division",
                "nameEnShort": "IRE PR",
                "nameChs": "爱尔兰超级联赛",
                "nameChsShort": "爱超",
                "nameCht": "愛爾蘭超級聯賽",
                "nameChtShort": "愛超",
                "type": "1",
                "subSclassEn": "League",
                "subSclassCn": "联赛",
                "sumRound": "36",
                "currRound": "1",
                "currSeason": "2020",
                "countryId": "16",
                "countryEn": "Ireland",
                "countryCn": "爱尔兰",
                "leagueLogo": "http://zq.win007.com/Image/league_match/images/20181129190115.png",
                "countryLogo": "http://zq.win007.com/Image/info/images/200712304261564347.gif",
                "areaId": "1"
            },
            {
                "leagueId": 2,
                "color": "#00CCCC",
                "nameEn": "Argentine Division 1",
                "nameEnShort": "ARG D1",
                "nameChs": "阿根廷甲级联赛",
                "nameChsShort": "阿甲",
                "nameCht": "阿根廷甲級聯賽",
                "nameChtShort": "阿甲",
                "type": "1",
                "subSclassEn": "League",
                "subSclassCn": "联赛",
                "sumRound": "23",
                "currRound": "18",
                "currSeason": "2019-2020",
                "countryId": "38",
                "countryEn": "Argentina",
                "countryCn": "阿根廷",
                "leagueLogo": "http://zq.win007.com/Image/league_match/images/20130917105542.jpg",
                "countryLogo": "http://zq.win007.com/Image/info/images/20130121182844.jpg",
                "areaId": "2"
            },
            {
                "leagueId": 3,
                "color": "#2f3fd2",
                "nameEn": "Austrian Bundesliga",
                "nameEnShort": "AUT D1",
                "nameChs": "奥地利甲组联赛",
                "nameChsShort": "奥甲",
                "nameCht": "奧地利甲組聯賽",
                "nameChtShort": "奧甲",
                "type": "1",
                "subSclassEn": "League",
                "subSclassCn": "联赛",
                "sumRound": "22",
                "currRound": "19",
                "currSeason": "2019-2020",
                "countryId": "14",
                "countryEn": "Austria",
                "countryCn": "奥地利",
                "leagueLogo": "http://zq.win007.com/Image/league_match/images/20140122115024.jpg",
                "countryLogo": "http://zq.win007.com/Image/info/images/20130801165112.jpg",
                "areaId": "1"
            },
            {
                "leagueId": 4,
                "color": "#996600",
                "nameEn": "Brazil Serie A",
                "nameEnShort": "BRA D1",
                "nameChs": "巴西甲组联赛",
                "nameChsShort": "巴西甲",
                "nameCht": "巴西甲組聯賽",
                "nameChtShort": "巴西甲",
                "type": "1",
                "sumRound": "38",
                "currRound": "38",
                "currSeason": "2019",
                "countryId": "39",
                "countryEn": "Brazil",
                "countryCn": "巴西",
                "leagueLogo": "http://zq.win007.com/Image/league_match/images/20191218144310.png",
                "countryLogo": "http://zq.win007.com/Image/info/images/20130121200051.jpg",
                "areaId": "2"
            },
            {
                "leagueId": 5,
                "color": "#FC9B0A",
                "nameEn": "Belgian Pro League",
                "nameEnShort": "BEL D1",
                "nameChs": "比利时甲组联赛",
                "nameChsShort": "比甲",
                "nameCht": "比利時甲組聯賽",
                "nameChtShort": "比甲",
                "type": "1",
                "subSclassEn": "League",
                "subSclassCn": "联赛",
                "sumRound": "30",
                "currRound": "24",
                "currSeason": "2019-2020",
                "countryId": "9",
                "countryEn": "Belgium",
                "countryCn": "比利时",
                "leagueLogo": "http://zq.win007.com/Image/league_match/images/20181204180011.png",
                "countryLogo": "http://zq.win007.com/Image/info/images/20130121180759.jpg",
                "areaId": "1"
            }
        ]
}