'use strict';

exports.getTeams = () => {
    return {
        teams: [{
            _id: '5e37bad26bb2c84577d30720',
            teamId: 180,
            leagueId: 1,
            nameEn: "Bohemians",
            nameChs: "波希米亚人",
            nameCht: "布咸美恩斯",
            foundingDate: "1890-9-6",
            areaEn: "Dublin",
            areaCn: "都柏林",
            gymEn: "Dalymount Park",
            gymCn: "戴利蒙特公园球场",
            capacity: "14500",
            logo: "http://zq.win007.com/Image/team/images/20130407085322.png",
            addrEn: "Dalymount Park Phibsborough IE - DUBLIN 7",
            addrCn: "Dalymount Park Phibsborough IE - DUBLIN 7",
            website: "http://www.bohemians.ie/",
            coachEn: "",
            coachCn: ""
        },
        {
            _id: '5e37bad26bb2c84577d3071d',
            teamId: 177,
            leagueId: 1,
            nameEn: "Shamrock Rovers",
            nameChs: "沙姆洛克流浪",
            nameCht: "沙姆洛克流浪",
            foundingDate: "1901",
            areaEn: "DUBLIN",
            areaCn: "都柏林",
            gymEn: "Tallaght Stadium",
            gymCn: "Tallaght Stadium",
            capacity: "",
            logo: "http://zq.win007.com/Image/team/images/20130407085823.png",
            addrEn: "Unit 12A Enterprise Center Main St. Tallaght Dublin 24 IRL IE - DUBLIN...",
            addrCn: "Unit 12A Enterprise Center Main St. Tallaght Dublin 24 IRL IE - DUBLIN...",
            website: "http://www.shamrockrovers.ie/",
            coachEn: "",
            coachCn: "",
        },
        {
            _id: '5e37bad26bb2c84577d3078f',
            teamId: 312,
            leagueId: 1,
            nameEn: "Derry City",
            nameChs: "德利城",
            nameCht: "德利城",
            foundingDate: "1984",
            areaEn: "Derry City",
            areaCn: "德利城",
            gymEn: "Brandywell Stadium",
            gymCn: "白兰地球场",
            capacity: "9000",
            logo: "http://zq.win007.com/Image/team/images/20130407090151.png",
            addrEn: "The Brandywell Stadium Lone Moor Road GB - DERRY BT48",
            addrCn: "The Brandywell Stadium Lone Moor Road GB - DERRY BT48",
            website: "http://www.derrycityfc.net",
            coachEn: "",
            coachCn: "",
        },
        {
            _id: '5e37bad26bb2c84577d30792',
            teamId: 315,
            leagueId: 1,
            nameEn: "Shelbourne",
            nameChs: "谢尔伯恩",
            nameCht: "舒爾本",
            foundingDate: "1895",
            areaEn: "Dublin",
            areaCn: "爱尔兰都柏林",
            gymEn: "Tolka Park",
            gymCn: "Tolda Park",
            capacity: "9681",
            logo: "http://zq.win007.com/Image/team/images/20130407090421.png",
            addrEn: "Tolka Park Drumcondra IE - DUBLIN 3",
            addrCn: "Tolka Park Drumcondra IE - DUBLIN 3",
            website: "http://www.shelbournefc.ie",
            coachEn: "Owen Heary",
            coachCn: "欧文希利",
        },
        {
            _id: '5e37bad26bb2c84577d30794',
            teamId: 317,
            leagueId: 1,
            nameEn: "Waterford United",
            nameChs: "沃特福德联队",
            nameCht: "屈福特聯",
            foundingDate: "1930",
            areaEn: "Waterford",
            areaCn: "爱尔兰",
            gymEn: "Regional Sports Centre",
            gymCn: "Regional Sports Centre",
            capacity: "8250",
            logo: "http://zq.win007.com/Image/team/images/20130408193035.png",
            addrEn: "RSC- Regional Sports Centre Cork Road IE- WATERFORD",
            addrCn: "RSC- Regional Sports Centre Cork Road IE- WATERFORD",
            website: "http://www.waterford-united.ie/",
            coachEn: "Roddy Collins",
            coachCn: "R.柯林斯",
        },
        {
            _id: '5e37bad26bb2c84577d3079b',
            teamId: 324,
            leagueId: 1,
            nameEn: "Cork City",
            nameChs: "科克城",
            nameCht: "曲克城",
            foundingDate: "1984-7-1",
            areaEn: "Cork",
            areaCn: "曲克",
            gymEn: "Turners Cross Stadium",
            gymCn: "特纳斯克球场",
            capacity: "9000",
            logo: "http://zq.win007.com/Image/team/images/20130407091421.png",
            addrEn: "Turner's Cross stadium Curragh Road IE - CORK",
            addrCn: "Turner's Cross stadium Curragh Road IE - CORK",
            website: "http://corkcityfc.ie/",
            coachEn: "John Caulfield",
            coachCn: "J.卡菲德",
        },
        {
            _id: '5e37bad26bb2c84577d307a3',
            teamId: 332,
            leagueId: 1,
            nameEn: "St. Patricks Athletic",
            nameChs: "圣帕特里克",
            nameCht: "聖巴特里",
            foundingDate: "1929",
            areaEn: "Dublin",
            areaCn: "都柏林",
            gymEn: "Richmond Park",
            gymCn: "里士满公园球场",
            capacity: "7000",
            logo: "http://zq.win007.com/Image/team/images/20130407093224.png",
            addrEn: "Saint Patricks Athletic Football Club Philip MOONEY Richmond Park 125 ...",
            addrCn: "Saint Patricks Athletic Football Club Philip MOONEY Richmond Park 125 ...",
            website: "http://www.stpatsfc.com/",
            coachEn: "",
            coachCn: "",
        },
        {
            _id: '5e37bad26bb2c84577d30ab4',
            teamId: 1251,
            leagueId: 1,
            nameEn: "Sligo Rovers",
            nameChs: "斯莱戈流浪",
            nameCht: "斯萊戈",
            foundingDate: "1928",
            areaEn: "Sligo",
            areaCn: "斯萊戈",
            gymEn: "The Showgrounds",
            gymCn: "The Showgrounds",
            capacity: "9000",
            logo: "http://zq.win007.com/Image/team/images/20130407093648.png",
            addrEn: "The Showgrounds, Sligo, Co. Sligo, Ireland",
            addrCn: "The Showgrounds, Sligo, Co. Sligo, Ireland",
            website: "http://www.sligorovers.com",
            coachEn: "",
            coachCn: "",
        },
        {
            _id: '5e37bad26bb2c84577d30af7',
            teamId: 1322,
            leagueId: 1,
            nameEn: "Finn Harps",
            nameChs: "费恩夏普",
            nameCht: "費恩夏普",
            foundingDate: "1954",
            areaEn: "Donegal",
            areaCn: "Donegal",
            gymEn: "Finn Park",
            gymCn: "Finn Park",
            capacity: "8400",
            logo: "http://zq.win007.com/Image/team/images/20130408193931.png",
            addrEn: "Finn Park, Ballybofey, Co. Donegal",
            addrCn: "Finn Park, Ballybofey, Co. Donegal",
            website: "http://www.finnharps.com/",
            coachEn: "",
            coachCn: "",
        },
        {
            _id: '5e37bad26bb2c84577d30b08',
            teamId: 1345,
            leagueId: 1,
            nameEn: "Dundalk",
            nameChs: "登克尔克",
            nameCht: "登克爾克",
            foundingDate: "1903",
            areaEn: "Dundalk",
            areaCn: "登克爾克",
            gymEn: "Oriel Park",
            gymCn: "奥丽尔公园球场",
            capacity: "13600",
            logo: "http://zq.win007.com/Image/team/images/20130408191151.png",
            addrEn: "Oriel Park, Carrick Road, Dundalk, Co. Louth, Ireland",
            addrCn: "Oriel Park, Carrick Road, Dundalk, Co. Louth, Ireland",
            website: "http://www.dundalkfc.com",
            coachEn: "Stephen Kenny",
            coachCn: "S.肯尼",
        }]
    };
}